/**爬虫数据列表查询条件*/
export const CRAWLER_CUR_PAGE = 'CRAWLER_CUR_PAGE';
export const CRAWLER_PAGE_SIZE = 'CRAWLER_PAGE_SIZE';
export const CRAWLER_FB_NAME = 'CRAWLER_FB_NAME';
export const CRAWLER_USERNAME = 'CRAWLER_USERNAME';
export const CRAWLER_STATUS = 'CRAWLER_STATUS';
export const CRAWLER_CHOSE_TIME = 'CRAWLER_CHOSE_TIME';
export const CURRENT_TAG = 'CURRENT_TAG';
export const TAGS = 'TAGS';

/**入库数据列表查询条件*/
export const INSTORE_CUR_PAGE = 'INSTORE_CUR_PAGE';
export const INSTORE_PAGE_SIZE = 'INSTORE_PAGE_SIZE';
export const INSTORE_FB_NAME = 'INSTORE_FB_NAME';
export const INSTORE_USERNAME = 'INSTORE_USERNAME';
export const INSTORE_CHOSE_TIME = 'INSTORE_CHOSE_TIME';
